### ISSUE TITLE
linkki 0.9.20180125 and Vaadin 8.3.1

### ISSUE THREAD

**Issue by belaso** [linkki-framework/linkki#1]
Hi linkki developers,

I want to use the newest linkki 0.9.20180125 version with Vaadin 8.3.1 (also newest 8.x version). I get following stackstace after starting a trivial Vaadin application (with `mvn jetty:run`):

```
java.lang.NullPointerException
	at com.vaadin.cdi.internal.AnnotationUtil.getUiBeans(AnnotationUtil.java:80)
	at com.vaadin.cdi.internal.ContextDeployer.discoverUIMappingsFromAnnotations(ContextDeployer.java:119)
	at com.vaadin.cdi.internal.ContextDeployer.contextInitialized(ContextDeployer.java:63)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:837)
```

and the Vaadin application don't start. Without linkki in my classpath everything looks ok. Is linkki working with Vaadin 8?

**Comment by cdir** [comment]
Hi @belaso,
thank you for the issue, actually the first one on github :)

Linkki could not work with vaadin 8 at the moment. I think the NPE in AnnotationUtil is the lowest problem. Linkki is instantiating all the vaadin components and handles every communication with them. The API breaks in vaadin 8 are far too much.

But good news: we are currently working on migrating linkki to vaadin 8.x. I think we will get a stable version within the next few weeks.

**Comment by belaso** [comment]
Hi @cdir,

thanks for the quick answer :+1: 

>But good news: we are currently working on migrating linkki to vaadin 8.x. I think we will get a stable version within the next few weeks.
Oh very nice, I will try Vaadin 8 with linkki the next few week.

**Comment by belaso** [comment]
Hi @cdir,

I get the same NPE also with Vaadin 7.7.13, but only if I start the application with `jetty:run`. I think that this a issue is with Jetty and Linkki, with Wildfly 11 there are no errors.

**Comment by cdir** [comment]
@belaso just saw that the NPE is from vaadin-cdi. You may try to use the latest vaadin-cdi dependency. I think in the latest released linkki version we still reference vaadin-cdi 1.0.3 - there were some intersting fixes in 1.0.5. Just upraded in master branch last week.

We also are working on making linkki cdi independent.

**Comment by belaso** [comment]
@cdir I tried Vaadin version 7.7.11 (see also linkki pom.xml) and linkki version 0.9.20180125 and I get the same NPE (see above) with `mvn jetty:run` and `mvn tomee:run`.

With Wildfly 11 everything works ok. I think, linkki requires something that does not exists in in Jetty and Tomcat but in Wildfly.

Can you reproduce the NPE with Jetty?

**Comment by cdir** [comment]
@belaso this might be any vaadin setup problem. You may have a look at our samples in this git repo, these samples all run with `mvn tomee:run` - I did not test `mvn jetty:run` yet.

**Comment by cdir** [comment]
@belaso just for your information: we already had tested the vaadin 8 migration but came to the conclusion that the performance of vaadin 8 with many grids/tables on one page is too slow. Unfortunately this is one of our main usecases in our customer projects. At the moment we look forward to vaadin 10 and wait to be feature complete.

**Comment by belaso** [comment]
Hi @cdir, thanks for the information. In my actual linkki project in Hannover Vaadin 8 is not an issue.
